name: Python CI/CD

on: [push]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: List project files (debug)
      run: ls -la  # Для отладки - покажет файлы в репозитории
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "Файл requirements.txt не найден! Создаю минимальный..."
          echo "flask" > requirements.txt
          pip install -r requirements.txt
        fi
